### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Lawaxi** [imorland/level-ranks#2]
Hello, I am a user of your level-ranks plugin. I changed some codes in my **vendor** folder, but it hadn't changed in my forum. Do you know why, what do I need then? Thank you for replying me, best wishes.

**Comment by Lawaxi** [comment]
Having learned the working style of composer, I have solved my problems. Thank you. In addition, you can add
`@media @phone {
    .PostUser-level {
        float: right;
        position: relative;
        margin-right: 10px;
        margin-top: 0px;
        width: 64px;
        text-align: center;
    }
}
`
in your forum.less so that it will support mobile view.

**Comment by imorland** [comment]
![image](https://user-images.githubusercontent.com/16573496/172730817-efb2a50d-d9e9-4545-b91a-f829dc7eee3c.png)

Mobile view is supported from version `1.1.0` :)
